schema {
  query: Query
}

type Query @shareable {
  "Fetches an object given its ID."
  node("ID of the object." id: ID!): Node @lookup @shareable @cost(weight: "10")
  "Lookup nodes by a list of IDs."
  nodes("The list of node IDs." ids: [ID!]!): [Node]! @cost(weight: "10")
  order1ById(id: ID!): Order1 @cost(weight: "10")
  order2ById(id: ID!): Order2 @cost(weight: "10")
  orders: [IOrder!]! @cost(weight: "10")
  ordersByIds(ids: [Int!]!): [IOrder!]! @cost(weight: "10")
}

type Order1 implements Node & IOrder {
  id: ID!
  name: String!
  product: Product!
}

type Order2 implements Node & IOrder {
  id: ID!
  name: String!
  product: Product!
}

type Product {
  id: ID! @shareable
}

interface IOrder {
  id: ID!
  name: String!
  product: Product!
}

"The node interface is implemented by entities that have a global unique identifier."
interface Node {
  id: ID!
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"""
The @lookup directive is used within a source schema to specify output fields
that can be used by the distributed GraphQL executor to resolve an entity by
a stable key.
"""
directive @lookup on FIELD_DEFINITION

directive @shareable repeatable on OBJECT | FIELD_DEFINITION
